### ISSUE TITLE
MQTT topic using "mqtt_retain:" value

### ISSUE THREAD

**Issue by Cogginshome** [thejeffreystone/hassio_addons#39]
Hi as the title says 

if mqtt_retain:"true" 
my mqtt has a root topic true with all the info in it 
I can change it to false I get the same 

I'm currently have
mqtt_retain:"rtl_433" and all is not working fine 

current config that is working 

mqtt_host: 10.4.1.1
mqtt_port: 1883
mqtt_user: sdr
mqtt_password: aI9DgYFfGsG4LzFo
mqtt_topic: rtl_433
mqtt_retain: rtl_433
protocol: "-R 11 -R 40 -R 41 -R 55 -R 74 -R 73"
whitelist_enable: true
whitelist: ""
expire_after: 0
units: si
discovery_prefix: homeassistant
discovery_interval: 600
debug: "true"

Hostname d63406df-acurite2mqtt 
Current version: 0.3.17b

Home assistant install 
Home Assistant 2022.10.5
Supervisor 2022.10.0 Operating System 9.2 
Frontend 20221010.0 - latest

Hardware Home assistant Blue
 
I noticed this on update to 2022.10.5 and OS9.2
![Screenshot from 2022-10-23 15-18-03](https://user-images.githubusercontent.com/87495179/197411772-e4859b14-4df6-40b0-878e-b6780d686c05.png)

**Comment by HalideGlow** [comment]
Hello, 
I checked my install and saw the same issue. The entry.sh file has the` mqtt_topic `and `mqtt_retain` variables swapped. I also noticed that `config.json` declares `mqtt_retain` as a string instead of a boolean value in the schema. It really should be treated as a boolean as that's what the rtl_433 documentation shows it as. I can get a patch together unless someone else wants to.

**Comment by thejeffreystone** [comment]
Pushed this in the latest update,,,,finally.
